version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mini-url-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mini-url-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/urlShortenerDB
      - BASE_URL=http://localhost:5000
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./dummy-frontend
    container_name: mini-url-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
